spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: praveen127

#config:
#  import: optional:configserver:http://localhost:2222/

server:
  port: 8081
